# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
  
pool:
  vmImage: ubuntu-latest
  
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'armSky'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm start --resource-group $(RESOURCEGROUPNAME) --name $(VMNAME)'
    failOnStandardError: true

- script: |
    echo "Waiting for VM to be ready..."
    while [ $(az vm show -g $(RESOURCEGROUPNAME) -n $(VMNAME) --query 'powerState' -o tsv) != "VM running" ]; do
      sleep 10
    done
  displayName: 'Wait for VM to be ready'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'armSky'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '~/.build.sh'
    arguments: '--resource-group $(RESOURCEGROUPNAME) --name $(VMNAME)'